### ISSUE TITLE
[Error] Step task reference is invalid

### ISSUE THREAD

**Issue by PiotrWachulec** [giuliov/hugo-vsts-extension#22]
Hey!

I'm trying to use the latest version of the task, but I'm getting the below error:

> Step  task reference is invalid. The task name HugoTask is ambiguous. Specify one of the following identifiers to resolve the ambiguity: giuliovdev.hugo-extension.hugo-build-task.HugoTask, giuliovdev.hugo-extension.hugo-build-task-v2.HugoTask

<img width="426" alt="Zrzut ekranu 2022-01-16 o 23 18 49" src="https://user-images.githubusercontent.com/11841233/149680356-5916aa60-3b10-4cb1-9449-d694a7120264.png">

```
- task: HugoTask@2
        inputs:
          source: './'
          destination: '$(Build.ArtifactStagingDirectory)'
          extendedVersion: true
          baseURL: ...
```

Could you help me with that? I tried to run that task on Ubuntu-latest and VS2017-Win2016 machines. Many thanks in advance!
