### ISSUE TITLE
Task fails with Hugo v0.93.0

### ISSUE THREAD

**Issue by ArnoPeters** [giuliov/hugo-vsts-extension#23]
A hardcoded flag --i18n-warnings is set in HugoTask.ts (v2, line 44), which has been renamed in Hugo version 0.93.0 to printI18nWarnings. This breaks the build as I cannot overwrite or omit this parameter from the task. 
Discovered because my build was set to use "latest" Hugo version. 

See 
https://github.com/gohugoio/hugo/releases/tag/v0.93.0

**Comment by bjornbouetsmith** [comment]
I can confirm this.

I did not change any settings in the plugin when I initially installed it.

So perhaps a way to "fix" this going forward is to "hardcode" the version in the plugin, so it uses the version that was "latest" when the version of this task built - so if people want to experiement, then they can actively change it to latest or a specific newer version?

**Comment by ArnoPeters** [comment]
I would rather that the no hardcoded parameters are used in the call to hugo.exe at all,  but that they can be toggled by a flag which can be disabled. I don't mind if the default is true, but if I can disable them I can then always overwrite them with a custom parameter. This also prevents the task from going obsolete or users having to monitor every hugo release.

I have now solved my build issue by sending in a specific version requirement into the plugin.

**Comment by johlju** [comment]
I temporarily worked around it by moving back to 0.92.2.

```
- task: giuliovdev.hugo-extension.hugo-build-task-v2.HugoTask@2
  displayName: 'Generate Hugo site'
  inputs:
    destination: '$(Build.ArtifactStagingDirectory)'
    hugoVersion: 0.92.2
```
